# Generated by Django 4.1.7 on 2023-03-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_addres_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('city',), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
