# Generated by Django 4.1.7 on 2023-03-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name', 'number_of_employees'), 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('department', 'name', 'surname'), 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('name',), 'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
    ]
