# Generated by Django 4.1.7 on 2023-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_address_city_alter_address_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='number_of_employees',
            field=models.IntegerField(default=0, verbose_name='Количество сотрудников'),
        ),
    ]
