# Generated by Django 4.1.7 on 2023-03-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_department_number_of_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.address', verbose_name='Адрес'),
        ),
    ]
