# Generated by Django 4.1.7 on 2023-03-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_university_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
