# Generated by Django 4.1.7 on 2023-03-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='univer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='University', to='app.university', verbose_name='Университет'),
            preserve_default=False,
        ),
    ]
