# Generated by Django 4.1.7 on 2023-03-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_address_univer_university_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='number_of_employees',
            field=models.IntegerField(default=0, max_length=255, null=True),
        ),
    ]
