# Generated by Django 4.1.7 on 2023-03-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_department_number_of_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='number_of_employees',
        ),
    ]
