# Generated by Django 4.1.7 on 2023-03-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='app.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='app.address', verbose_name='Адрес'),
        ),
    ]
